"""add components table

Revision ID: 0a840e6283b5
Revises: c0ff81156b6a
Create Date: 2026-04-07 20:49:25.733853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a840e6283b5'
down_revision: Union[str, Sequence[str], None] = 'c0ff81156b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_internal', sa.String(length=500), nullable=False),
    sa.Column('name_normalized', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('search_queries', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('enrichment_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_category_id'), 'components', ['category_id'], unique=False)
    op.create_index(op.f('ix_components_enrichment_status'), 'components', ['enrichment_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_components_enrichment_status'), table_name='components')
    op.drop_index(op.f('ix_components_category_id'), table_name='components')
    op.drop_table('components')
    # ### end Alembic commands ###
